### ISSUE TITLE
Crash on find_injection

### ISSUE THREAD

**Issue by kiranshila** [GReX-Telescope/GReX-T2#11]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/grex/t2/scripts/run_socket_grex.py", line 90, in main
    last_trigger_time = socket_grex.filter_candidates(
  File "/home/user/grex/t2/grex_t2/socket_grex.py", line 87, in filter_candidates
    tab4, lastname, last_trigger_time = cluster_heimdall.dump_cluster_results_json(
  File "/home/user/grex/t2/grex_t2/cluster_heimdall.py", line 349, in dump_cluster_results_json
    injection_id = database.find_injection(mjd, db_con)
  File "/home/user/grex/t2/grex_t2/database.py", line 47, in find_injection
    if len(res) == 1:
TypeError: object of type 'NoneType' has no len()
```

**Comment by kiranshila** [comment]
JK, this was an issue in my fork.
